// Export pages
export '/i2_s_app_folder/signup_page_option1/signup_page_option1_widget.dart'
    show SignupPageOption1Widget;
export '/i2_s_app_folder/splash_screen/splash_screen_widget.dart'
    show SplashScreenWidget;
export '/for_intern/dashboard_for_interns/dashboard_for_interns_widget.dart'
    show DashboardForInternsWidget;
export '/for_intern/homepage_sample_option1/homepage_sample_option1_widget.dart'
    show HomepageSampleOption1Widget;
export '/dashboard_for_universities/dashboard_for_universities_widget.dart'
    show DashboardForUniversitiesWidget;
export '/i2_s_app_folder/login_page/login_page_widget.dart'
    show LoginPageWidget;
export '/for_intern/user_profile_intern/user_profile_intern_widget.dart'
    show UserProfileInternWidget;
export '/for_intern/privacy_support/privacy_support_widget.dart'
    show PrivacySupportWidget;
export '/for_intern/internshiptab_intern_pathway_o2/internshiptab_intern_pathway_o2_widget.dart'
    show InternshiptabInternPathwayO2Widget;
export '/for_intern/my_application/my_application_widget.dart'
    show MyApplicationWidget;
export '/for_intern/wishlist_saved_internship/wishlist_saved_internship_widget.dart'
    show WishlistSavedInternshipWidget;
export '/for_intern/logout/logout_widget.dart' show LogoutWidget;
export '/saved_pages_for_interns/dashboard_for_interns_copy/dashboard_for_interns_copy_widget.dart'
    show DashboardForInternsCopyWidget;
export '/saved_pages_for_interns/homepage_sample_option1_copy/homepage_sample_option1_copy_widget.dart'
    show HomepageSampleOption1CopyWidget;
export '/saved_pages_for_interns/internshiptab_intern_pathway_o2_copy/internshiptab_intern_pathway_o2_copy_widget.dart'
    show InternshiptabInternPathwayO2CopyWidget;
export '/saved_pages_for_interns/logout_copy/logout_copy_widget.dart'
    show LogoutCopyWidget;
export '/saved_pages_for_interns/my_application_copy/my_application_copy_widget.dart'
    show MyApplicationCopyWidget;
export '/saved_pages_for_interns/privacy_support_copy/privacy_support_copy_widget.dart'
    show PrivacySupportCopyWidget;
export '/saved_pages_for_interns/wishlist_saved_internship_copy/wishlist_saved_internship_copy_widget.dart'
    show WishlistSavedInternshipCopyWidget;
export '/for_intern/notification_bar/notification_bar_widget.dart'
    show NotificationBarWidget;
export '/saved_pages_for_interns/notification_bar_copy/notification_bar_copy_widget.dart'
    show NotificationBarCopyWidget;
export '/for_intern/setting_page/setting_page_widget.dart'
    show SettingPageWidget;
export '/saved_pages_for_interns/setting_page_copy/setting_page_copy_widget.dart'
    show SettingPageCopyWidget;
export '/for_intern/training_tab_o4/training_tab_o4_widget.dart'
    show TrainingTabO4Widget;
export '/saved_pages_for_interns/training_tab_o4_copy/training_tab_o4_copy_widget.dart'
    show TrainingTabO4CopyWidget;
export '/for_intern/guidence_tab_02/guidence_tab02_widget.dart'
    show GuidenceTab02Widget;
export '/for_intern/resume_tab_o3/resume_tab_o3_widget.dart'
    show ResumeTabO3Widget;
export '/saved_pages_for_interns/guidence_tab_02_copy/guidence_tab02_copy_widget.dart'
    show GuidenceTab02CopyWidget;
export '/saved_pages_for_interns/resume_tab_o3_copy/resume_tab_o3_copy_widget.dart'
    show ResumeTabO3CopyWidget;
export '/for_university/home_page_universities/home_page_universities_widget.dart'
    show HomePageUniversitiesWidget;
export '/saved_pages_for_univer/home_page_universities_copy/home_page_universities_copy_widget.dart'
    show HomePageUniversitiesCopyWidget;
export '/for_university/our_services/our_services_widget.dart'
    show OurServicesWidget;
export '/for_university/about_internships/about_internships_widget.dart'
    show AboutInternshipsWidget;
export '/saved_pages_for_univer/about_internships_copy/about_internships_copy_widget.dart'
    show AboutInternshipsCopyWidget;
export '/saved_pages_for_univer/our_services_copy/our_services_copy_widget.dart'
    show OurServicesCopyWidget;
export '/for_university/profile_page_universities/profile_page_universities_widget.dart'
    show ProfilePageUniversitiesWidget;
export '/saved_pages_for_univer/profile_page_universities_copy/profile_page_universities_copy_widget.dart'
    show ProfilePageUniversitiesCopyWidget;
export '/for_cop/homepage_for_company_o1/homepage_for_company_o1_widget.dart'
    show HomepageForCompanyO1Widget;
export '/for_university/collaboration_page/collaboration_page_widget.dart'
    show CollaborationPageWidget;
export '/saved_pages_for_univer/collaboration_page_copy/collaboration_page_copy_widget.dart'
    show CollaborationPageCopyWidget;
export '/for_university/setting_page_universities/setting_page_universities_widget.dart'
    show SettingPageUniversitiesWidget;
export '/saved_pages_for_interns/user_profile_intern_copy/user_profile_intern_copy_widget.dart'
    show UserProfileInternCopyWidget;
export '/saved_pages_for_univer/setting_page_universities_copy/setting_page_universities_copy_widget.dart'
    show SettingPageUniversitiesCopyWidget;
export '/for_cop/service_tab_company_o2/service_tab_company_o2_widget.dart'
    show ServiceTabCompanyO2Widget;
export '/for_cop/collaborate_tab_for_company_o1/collaborate_tab_for_company_o1_widget.dart'
    show CollaborateTabForCompanyO1Widget;
export '/for_university/notification_page/notification_page_widget.dart'
    show NotificationPageWidget;
export '/for_cop/postinternship_tab_for_company_o2/postinternship_tab_for_company_o2_widget.dart'
    show PostinternshipTabForCompanyO2Widget;
export '/saved_pages_for_univer/notification_page_copy/notification_page_copy_widget.dart'
    show NotificationPageCopyWidget;
export '/for_university/partnership_page/partnership_page_widget.dart'
    show PartnershipPageWidget;
export '/for_university/partnership_page_2/partnership_page2_widget.dart'
    show PartnershipPage2Widget;
export '/for_gov/program_initiative_goverment/program_initiative_goverment_widget.dart'
    show ProgramInitiativeGovermentWidget;
export '/for_gov/homepage_gov_o4/homepage_gov_o4_widget.dart'
    show HomepageGovO4Widget;
export '/for_gov/collaboration_pages/collaboration_pages_widget.dart'
    show CollaborationPagesWidget;
export '/for_gov/profile_goverement/profile_goverement_widget.dart'
    show ProfileGoverementWidget;
export '/for_gov/our_service_gover/our_service_gover_widget.dart'
    show OurServiceGoverWidget;
export '/for_cop/profilepage_company_o1/profilepage_company_o1_widget.dart'
    show ProfilepageCompanyO1Widget;
export '/for_gov/setting_page_gover/setting_page_gover_widget.dart'
    show SettingPageGoverWidget;
